20200408
kota-1248/portfolio pull request #3
Opened 2020-04-08 09:22 UTC by kota-1248

# レビュー観点
何をレビューしてもらいたいのか？
# 変更内容／作業内容
 - [ ] 作業内容１
 - [ ] 作業内容２
 - [ ] 作業内容３
〜中略〜
 - [ ] 作業内容Ｎ
# Before（画面に変更がある場合）
変更前のスクリーンショット（イメージ）をドラッグ＆ドロップで貼り付け
# After （画面に変更がある場合）
変更前のスクリーンショット（イメージ）をドラッグ＆ドロップで貼り付け

2020-04-08 12:10 UTC, hidekishibashi requested changes
現状のdevelopと同じコミットをもつmasterができてからマージしたいので、一旦STAY

2020-04-08 12:10 UTC, hidekishibashi commented on src/main.js
> +import './assets/css/reset.css'
これ3行目にあるのが自然かと。

2020-04-08 12:10 UTC, hidekishibashi commented on src/components/Header.vue
> +
不要な改行です

2020-04-08 12:10 UTC, hidekishibashi commented on src/App.vue
> +    <Footer />
templateがないcomponentはエラーが起きるはず

2020-04-08 12:10 UTC, hidekishibashi commented
PR名を指定されたものに修正お願いします

2020-04-09 01:15 UTC, kota-1248 commented
修正部分承知致しました。

2020-04-24 08:57 UTC, closed without merging